spring:
  application:
    name: auth-service
  data:
    cassandra:
      contact-points: 127.0.0.1
      port: 9042
      local-datacenter: datacenter1
      keyspace-name: auth_keyspace
      schema-action: CREATE_IF_NOT_EXISTS

jwt:
  private-key: classpath:keys/private.pem
  public-key: classpath:keys/public.pem
  expired-date: 3600000

eureka:
  client:
    service-url:
      defaultZone : http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true

  instance:
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 10

server:
  port: 8081

management:
  tracing:
    sampling:
      probability: 1.0
    export:
      zipkin:
        endpoint: http://localhost:9411/api/v2/spans

logging:
  level:
    com.datastax.oss.driver: INFO
    org.cognitor.cassandra: DEBUG
    org.springframework.data.cassandra: DEBUG