spring:
  application:
    name: auth-service

jwt:
  private-key: classpath:keys/private.pem
  public-key: classpath:keys/public.pem
  expired-date: 3600000

eureka:
  client:
    service-url:
      defaultZone : http://host.docker.internal:8761/eureka/