services:
  cassandra:
    image: cassandra:5
    container_name: cassandra
    ports:
      - "9042:9042"
    environment:
      CASSANDRA_KEYSPACE: auth_keyspace
    healthcheck:
      test: [ "CMD-SHELL", "cqlsh -u cassandra -p cassandra -e \"describe keyspaces\"" ]
      interval: 10s
      timeout: 5s
      retries: 5

  auth-service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: auth-service
    depends_on:
      cassandra:
        condition: service_healthy
    environment:
      SPRING_PROFILES_ACTIVE: default

name: auth-service-compose